### ISSUE TITLE
em에 대한 질문

### ISSUE THREAD

**Issue by Cheolsker** [CodeSoom/project-react-6-CheolWoongChoi#25]
트레이너님! 안녕하세요

전에 다양한 기기에 대응을 할 때, em을 쓰면 좋다고 피드백을 주셨는데요.
몇 가지 궁금한 부분이 생겼습니다!

1. em 단위를 사용한다고 할 때, 협업을 할 때 어떻게 소통을 하는 지 궁금합니다.
가령, 제플린이나 피그마를 통해 디자이너가 UI를 공유해줄 때 px단위로 디자인을 많이 하는데요.
em을 사용하려면 px을 한번 더 변환해주어야 하는 걸로 알고 있습니다. 
그리고 기기의 화면마다 크기가 다를 수 있는데 이것을 어떻게 대응해줘야 하는지 궁금합니다.

2. 단위변환이 어렵거나, 복잡하다고 느끼면 rem을 사용하는 것이 더 효과적이지 않나요?
기기에 따라 root 태그 (html)의 font-size만 변환해주면 되지 않나 하는 생각이 듭니다.

**Comment by moonkii** [comment]
> 기기의 화면마다 크기가 다를 수 있는데 이것을 어떻게 대응해줘야 하는지 궁금합니다.

저희 회사에서는 크게 모바일, 데스크탑로 나누어서 작업하는데 디바이스에 따라 적절한 단위를 사용해줘서 맞춰주는 편이에요.
디자이너가 세부단위까지 모두 지정해서 디자인해준다면 그에 맞춰 따라가면되지만 그렇게 하나하나 다 잡아주지 않는 경우 적당히 `em` 을 이용해서 맞춰주는 편이에요.

> 단위변환이 어렵거나, 복잡하다고 느끼면 rem을 사용하는 것이 더 효과적이지 않나요?
기기에 따라 root 태그 (html)의 font-size만 변환해주면 되지 않나 하는 생각이 듭니다.

딱 하나만 정해서 사용한다기 보다 필요에 따라 적절하게 사용한다 생각하시면 좋을 것 같아요.

**Comment by Cheolsker** [comment]
한 가지 더 궁금한 부분이 있는데요.
어떤 회사에서는 자체적인 디자인 시스템을 구축하고 있는데 (토스의 경우 TDS),
퍼블리싱 부분은 되도록 자동화시키고, 프론트엔드 개발자는 비즈니스 로직 위주로 프로젝트를 진행한다고 들은 바 있습니다.

퍼블리싱 부분 (리액트에서 UI적인 요소)을 자동화할 수 있는 방법이 있을까요?
그리고 프론트엔드 개발자의 역할이 상황에 따라 달라지는 것 같은데 이 부분도 궁금합니다.

**Comment by moonkii** [comment]
> 퍼블리싱 부분 (리액트에서 UI적인 요소)을 자동화할 수 있는 방법이 있을까요?
그리고 프론트엔드 개발자의 역할이 상황에 따라 달라지는 것 같은데 이 부분도 궁금합니다.

퍼블리싱하는 사람을 따로 두지 않으면 figma 같은 툴로 대신할수도 있어요.
토스같은 회사는 디자인 시스템을 체계적으로 잘 만들어놔서 가능한 구조고, 대부분은 프론트 개발자가 같이하는 편이죠.
상황에 따라 역할이 달라지기보단 업무가 더 늘어날 순 있겠죠?
