### ISSUE TITLE
테스트 코드에서 JS 외의 다른 파일을 처리하기

### ISSUE THREAD

**Issue by Cheolsker** [CodeSoom/project-react-6-CheolWoongChoi#3]
CSS 파일을 import 했을 때, 테스트 코드에서 CSS 구문을 인식하지 못한 오류가 발생했습니다.
구글링을 해보니, Jest 설정에서 moduleNameWrapper를 이용하라고 하네요.

https://stackoverflow.com/questions/39418555/syntaxerror-with-jest-and-react-and-importing-css-files
https://jestjs.io/docs/configuration#modulenamemapper-objectstring-string--arraystring

모듈을 import 할 때, 파일 경로를 정규표현식으로 판단해서 다른 파일 경로로 대체하는 것 같습니다.
모킹(mocking)을 통해 대체할 수도 있고요.

identify-obj-proxy를 이용해보라는 이야기도 있었는데, 생소하기도 하고 라이브러리 업데이트가 안된지 한참 되어서 사용하진 않았습니다.

https://www.npmjs.com/package/identity-obj-proxy

**Comment by moonkii** [comment]
설정파일쪽을 알아보셔도 도움이 될 것 같네요.

**Comment by Cheolsker** [comment]
> 설정파일쪽을 알아보셔도 도움이 될 것 같네요.

Jest 설정말씀이시군요!
